import perfume1 from "@/assets/perfume-1.jpg";
import perfume2 from "@/assets/perfume-2.jpg";
import perfume3 from "@/assets/perfume-3.jpg";
import perfume4 from "@/assets/perfume-4.jpg";
import { Product } from "@/components/ProductCard";

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Noir Absolu",
    subtitle: "Eau de Parfum · 100ml",
    price: 285,
    priceDA: 38000,
    pricePerDecant: 4200,
    image: perfume1,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Bergamote, Poivre Noir" },
      { type: "middle", notes: "Oud, Rose, Safran" },
      { type: "base", notes: "Bois de Santal, Ambre, Musc" },
    ],
  },
  {
    id: "2",
    name: "Citrus Éclat",
    subtitle: "Eau de Toilette · 75ml",
    price: 195,
    priceDA: 26000,
    pricePerDecant: 3000,
    image: perfume2,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Bergamote, Citron, Pamplemousse" },
      { type: "middle", notes: "Menthe, Thé Vert, Cardamome" },
      { type: "base", notes: "Vétiver, Cèdre, Musc Blanc" },
    ],
  },
  {
    id: "3",
    name: "Fleur d'Or",
    subtitle: "Eau de Parfum · 100ml",
    price: 320,
    priceDA: 42500,
    pricePerDecant: 4800,
    image: perfume3,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Jasmin, Ylang-Ylang" },
      { type: "middle", notes: "Rose, Pivoine, Iris" },
      { type: "base", notes: "Vanille, Benjoin, Bois de Santal" },
    ],
  },
  {
    id: "4",
    name: "Oud Mystique",
    subtitle: "Parfum Intense · 50ml",
    price: 425,
    priceDA: 56500,
    pricePerDecant: 6500,
    image: perfume4,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Safran, Muscade" },
      { type: "middle", notes: "Oud, Cuir, Encens" },
      { type: "base", notes: "Ambre, Labdanum, Castoreum" },
    ],
  },
  {
    id: "5",
    name: "Vetiver Sauvage",
    subtitle: "Eau de Parfum · 100ml",
    price: 245,
    priceDA: 32500,
    pricePerDecant: 3500,
    image: perfume1,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Pamplemousse, Poivre Rose" },
      { type: "middle", notes: "Vétiver, Patchouli, Géranium" },
      { type: "base", notes: "Cèdre, Mousse de Chêne, Ambre Gris" },
    ],
  },
  {
    id: "6",
    name: "Leather Noir",
    subtitle: "Parfum · 75ml",
    price: 385,
    priceDA: 51200,
    pricePerDecant: 5800,
    image: perfume2,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Cardamome, Feuille de Violette" },
      { type: "middle", notes: "Cuir, Iris, Sauge Sclarée" },
      { type: "base", notes: "Vétiver, Fève Tonka, Patchouli" },
    ],
  },
  {
    id: "7",
    name: "Amber Royale",
    subtitle: "Eau de Parfum · 100ml",
    price: 310,
    priceDA: 41200,
    pricePerDecant: 4500,
    image: perfume4,
    category: "men",
    scentNotes: [
      { type: "top", notes: "Mandarine, Anis Étoilé" },
      { type: "middle", notes: "Cannelle, Myrrhe, Tabac" },
      { type: "base", notes: "Ambre, Vanille, Benjoin" },
    ],
  },
  {
    id: "8",
    name: "Rose Précieuse",
    subtitle: "Parfum · 50ml",
    price: 445,
    priceDA: 59200,
    pricePerDecant: 6800,
    image: perfume1,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Rose de Mai, Framboise" },
      { type: "middle", notes: "Rose de Turquie, Rose de Mai" },
      { type: "base", notes: "Musc, Ambre, Patchouli" },
    ],
  },
  {
    id: "9",
    name: "Ambre Solaire",
    subtitle: "Eau de Parfum · 100ml",
    price: 295,
    priceDA: 39200,
    pricePerDecant: 4200,
    image: perfume2,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Mandarine, Poivre Rose, Bergamote" },
      { type: "middle", notes: "Fleur d'Oranger, Tubéreuse, Jasmin" },
      { type: "base", notes: "Ambre, Vanille, Benjoin" },
    ],
  },
  {
    id: "10",
    name: "Iris Délicate",
    subtitle: "Eau de Toilette · 75ml",
    price: 215,
    priceDA: 28500,
    pricePerDecant: 3200,
    image: perfume3,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Néroli, Citron" },
      { type: "middle", notes: "Iris, Violette, Freesia" },
      { type: "base", notes: "Musc Blanc, Bois de Cèdre" },
    ],
  },
  {
    id: "11",
    name: "Vanille Exquise",
    subtitle: "Parfum Intense · 50ml",
    price: 395,
    priceDA: 52500,
    pricePerDecant: 6000,
    image: perfume4,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Bergamote, Mandarine" },
      { type: "middle", notes: "Jasmin, Fleur d'Oranger" },
      { type: "base", notes: "Vanille de Madagascar, Fève Tonka, Bois de Santal" },
    ],
  },
  {
    id: "12",
    name: "Pivoine Royale",
    subtitle: "Eau de Parfum · 100ml",
    price: 330,
    priceDA: 43800,
    pricePerDecant: 4900,
    image: perfume1,
    category: "women",
    scentNotes: [
      { type: "top", notes: "Cassis, Litchi" },
      { type: "middle", notes: "Pivoine, Rose, Magnolia" },
      { type: "base", notes: "Musc, Cèdre, Ambre" },
    ],
  },
];
